
services:
  db:
    image: postgres
    container_name: test_postgres2
    networks:
      dbnetwork:
          ipv4_address: 192.168.1.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD= password
      - POSTGRES_DB= testdb2
    volumes:
      - /home/vntchang/test_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    # ports:
    #     - "5432:5432" 

  user_auth_server:
    build: 
      context: ./hruserauth/
      args:
        - PORT=${UA_PORT}
    container_name: user_auth_server
    networks:
      - dbnetwork
      - bridge2
    depends_on:
      db:
        condition: service_healthy
    ports:
        - ${UA_PORT}:${UA_PORT}

  graphql_server:
    build: 
      context: ./hrGraphql/
      args:
        - PORT=${GQL_PORT}
    container_name: graphql_server
    networks:
      - dbnetwork
      - bridge2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${GQL_PORT}:${GQL_PORT}

  racetrack_maker_server:
    build:
      context: ./racetrack_maker/
    container_name: racetrack_maker
    networks:
      - bridge2
    ports:
      - ${RM_PORT}:${RM_PORT}

  personal_site_server:
    build: 
      context: ./personal_site/
      args:
        - PORT=${PS_PORT}
    container_name: personal_site
    networks:
      - bridge2
    ports:
      - ${PS_PORT}:${PS_PORT}
    
  
networks:
  dbnetwork:
    name: dbnetwork
    ipam:
      config:
        - subnet: 192.168.1.0/24
    internal: true
  bridge2:
    name: bridge2
